/* Writes site/js/manifest.js — the byte-accurate preload manifest.
   Every entry: [url, bytes, width, height]. The loading screen streams each
   file and reports real progress against the summed byte total. */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const dirs = ["site/assets/art", "site/assets/fx"];

function dims(file) {
  try {
    const out = execFileSync("identify", ["-format", "%w %h", file + "[0]"], {
      encoding: "utf8",
    });
    return out.trim().split(/\s+/).map(Number);
  } catch (e) {
    return [0, 0];
  }
}

const entries = [];
for (const d of dirs) {
  const abs = path.join(ROOT, d);
  if (!fs.existsSync(abs)) continue;
  for (const f of fs.readdirSync(abs).sort()) {
    if (!/\.(webp|png|jpg|avif)$/i.test(f)) continue;
    const file = path.join(abs, f);
    const [w, h] = dims(file);
    entries.push([
      d.replace(/^site\//, "") + "/" + f,
      fs.statSync(file).size,
      w,
      h,
    ]);
  }
}

const total = entries.reduce((a, e) => a + e[1], 0);
const body =
  "/* generated by tools/write_manifest.js — do not edit by hand */\n" +
  '"use strict";\n' +
  "const MANIFEST = [\n" +
  entries.map((e) => "  " + JSON.stringify(e)).join(",\n") +
  "\n];\n" +
  "const MANIFEST_BYTES = " +
  total +
  ";\n";

fs.writeFileSync(path.join(ROOT, "site/js/manifest.js"), body);
console.log(
  `manifest: ${entries.length} files, ${(total / 1048576).toFixed(2)} MB`
);
